services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: kousu_app_development
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      RAILS_ENV: development
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:postgres@db:5432/kousu_app_development
    command: bash -lc "until pg_isready -h db -p 5432 -U postgres -t 1; do echo 'waiting for db'; sleep 1; done; bin/rails db:prepare && bin/rails s -b 0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
    tty: true
    stdin_open: true

volumes:
  pgdata:
  bundle:
  node_modules:
